[2025-04-04T08:59:18.517+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-03-15T00:00:00+00:00 [queued]>
[2025-04-04T08:59:18.612+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-03-15T00:00:00+00:00 [queued]>
[2025-04-04T08:59:18.616+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T08:59:18.618+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T08:59:18.621+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T08:59:18.725+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_images> on 2023-03-15 00:00:00+00:00
[2025-04-04T08:59:18.761+0000] {standard_task_runner.py:55} INFO - Started process 636 to run task
[2025-04-04T08:59:18.781+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'upload_images', 'scheduled__2023-03-15T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/dagv2_data_collect.py', '--cfg-path', '/tmp/tmpttva5nw6']
[2025-04-04T08:59:18.787+0000] {standard_task_runner.py:83} INFO - Job 156: Subtask upload_images
[2025-04-04T08:59:18.827+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T08:59:18.912+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T08:59:19.382+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.upload_images scheduled__2023-03-15T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T08:59:19.849+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=upload_images
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-15T00:00:00+00:00
[2025-04-04T08:59:19.913+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T08:59:19.922+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T08:59:19.929+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T08:59:23.720+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T08:59:23.726+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T08:59:25.455+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T08:59:25.516+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=upload_images, execution_date=20230315T000000, start_date=20250404T085918, end_date=20250404T085925
[2025-04-04T08:59:25.579+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T08:59:25.622+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
