[2025-04-04T08:57:25.608+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-04-04T08:57:25.641+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-04-04T08:57:25.642+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T08:57:25.643+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T08:57:25.644+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T08:57:25.699+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_images> on 2023-01-02 00:00:00+00:00
[2025-04-04T08:57:25.720+0000] {standard_task_runner.py:55} INFO - Started process 102 to run task
[2025-04-04T08:57:25.743+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'upload_images', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dagv2_data_collect.py', '--cfg-path', '/tmp/tmp1c_2r5ie']
[2025-04-04T08:57:25.753+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask upload_images
[2025-04-04T08:57:25.830+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T08:57:26.074+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T08:57:26.372+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.upload_images scheduled__2023-01-02T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T08:57:27.892+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=upload_images
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2025-04-04T08:57:28.009+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T08:57:28.029+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T08:57:28.042+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T08:57:37.354+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T08:57:37.359+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T08:57:42.531+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T08:57:42.728+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=upload_images, execution_date=20230102T000000, start_date=20250404T085725, end_date=20250404T085742
[2025-04-04T08:57:42.991+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T08:57:43.162+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
